<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TodoItem;
use Doctrine\ORM\EntityRepository;

/**
 * TodoItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoItemRepository extends EntityRepository
{

    /**
     * @return TodoItem[]
     */
    public function findAllOrdered()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function removeCompleted()
    {
        $this->createQueryBuilder('t')
            ->delete()
            ->where('t.completed = :true')
            ->setParameter('true', true)
            ->getQuery()
            ->execute();
    }

}
